name: Pipeline de Pruebas Continuas
on: [push, pull_request]
jobs:
pruebas:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

- name: Instalar Python
  uses: actions/setup-python@v5
  with:
  python-version: '3.13'
- name: Instalar dependencias
  run:
  pip Install pytest
- name: Ejecutar pruebas unitarias
  run: python -m unittest